# Listener
http.host=0.0.0.0
http.port=8081

# Anypoint Connected App
# Set via CloudHub 2.0 secure properties or environment variables
#anypoint.connected.app.client.id=bb7bbc355f4041cbb7416ffe0fc8e39a
#anypoint.connected.app.client.secret=32D680f253334186a2181A831d21C7A8
anypoint.connected.app.client.id=556d8f57e3904a92ae1cb8bcae628668
anypoint.connected.app.client.secret=6A41b25a79E54Aac8fE69a1A48c355d9


# API Manager Autodiscovery
# api.id is the API Instance ID from API Manager
#api.id=2775516
api.id=20976434
api.version=v1

#Treshold Metrics
threshold.cpu.percent=1
threshold.memory.percent=2
threshold.latency.ms=1000
threshold.error.count=500

# DashBoard BG
#dashboard.business.groups=BG1-RSA-LEVEL1
dashboard.business.groups=C4E-CMN
